### ISSUE TITLE
 Trying to access array offset on false... with PHP 8.3.9

### ISSUE THREAD

**Issue by kanglu** [over-engineer/link-verification-for-mastodon#11]
When I upgraded Wordpress 6.6.1 to use PHP 8.3.9

I received the following error:

AH01071: Got error 'PHP message: PHP Warning:  Trying to access array offset on false in
     ... wordpress/wp-content/plugins/link-verification-for-mastodon/includes/verification-tag.php on line 68'

For some reason the $options['mastodon_username'] passed into the apply_filters was empty or not set.

I changed it to $mastodon_username instead, since the previous line already provided a default.

https://github.com/over-engineer/link-verification-for-mastodon/blame/c82da11ade260006e4afbe6ac57dbe3a5345aa5b/includes/verification-tag.php#L68

**Comment by over-engineer** [comment]
Hey, @kanglu!

Thanks for spotting that issue and taking the time to report it.

This was addressed in the latest version, which was just released on the Plugin Directory.

**Comment by over-engineer** [comment]
Closing as resolved.
