### ISSUE TITLE
Malformed link?

### ISSUE THREAD

**Issue by marcoskirsch** [over-engineer/link-verification-for-mastodon#8]
Hello, I installed the plugin today and entered my account details, but the verification check didn't show up.
I looked at page source and found the `link` tag added by the plugin as follows (see linke 685 of [page](https://marcos.kirsch.mx)):

```html
...
    <style>
    img#wpstats {
        display: none
    }
    </style>
    <link rel="me" href="https://mastodon.world/@kirsch"/>
    <style type="text/css" id="twentyfourteen-header-css">
    .site-title a {
        color: #dd9933;
    }
    </style>
...
```

However, the [Mastodon profile edit page](https://mastodon.world/settings/profile) indicates that the link should be in the form:
```
<a rel="me" href="https://mastodon.world/@kirsch">Mastodon</a>
```

In other places I read that it's ok to leave the text empty as follows:
```
<a rel="me" href="https://mastodon.world/@kirsch"></a>
```
... which is what I expected this plugin to do.

**Comment by over-engineer** [comment]
Hey, @marcoskirsch!

Even though the profile edit page only mentions the following:

>You can **verify yourself as the owner of the links in your profile metadata**. For that, the linked website must contain a link back to your Mastodon profile. The link back **must** have a `rel="me"` attribute. The text content of the link does not matter. Here is an example:
>
>```
><a rel="me" href="https://fosstodon.org/@overengineer">Mastodon</a>
>```

using a `link` tag works as well.

The verify link service grabs all anchor (`a`) and `link` elements of the page you're attempting to verify.

[`mastodon/mastodon` repo, `verify_link_service.rb` ref](https://github.com/mastodon/mastodon/blob/main/app/services/verify_link_service.rb#L29):

```rb
def link_back_present?
    return false if @body.blank?

    links = Nokogiri::HTML5(@body).xpath('//a[contains(concat(" ", normalize-space(@rel), " "), " me ")]|//link[contains(concat(" ", normalize-space(@rel), " "), " me ")]')
```

Everything seems to be properly set up, so you might need to wait a bit longer before your website gets verified.

Try changing your url to something else → saving your profile → switching back to the actual url → saving the changes again — see if that triggers the link verification.

If that doesn't do the trick, please wait for a while. If the issue persists, leave another comment here, so I can take another look (in the meantime, I'll leave this issue open) 🙂

**Comment by over-engineer** [comment]
@marcoskirsch, I’m following up on this, since it’s been about a month and your website doesn’t seem to be verified.

I noticed that you’ve typed a mixed-case (i.e. containing both capital and lower case letters) link to your blog — `Marcos.Kirsch.mx`. That _could_ be what’s causing your link to not be verified.

Could you please switch to an all lowercase link (that would be `https://marcos.kirsch.mx`) and let me know if that resolves the issue?

**Comment by marcoskirsch** [comment]
I switched to all lower-case in my profile on the Mastodon server. That made it show up as verified immediately.
Thanks for the suggestion and for the help, I apologize if I wasted any of your time!

**Comment by over-engineer** [comment]
No worries! Thanks for following up with me, I’m glad it worked.

You’d expect that to be case insensitive — apparently that isn’t the case 🤷
